import { _decorator, Component, Node, Button, Event } from 'cc';
const { ccclass } = _decorator;

@ccclass
export default class auto_BattleUI extends Component {
	BattleUI: Node;
	battle_bg: Node;
	View: Node;
	PetLayer: Node;
	pet_left: Node;
	pet_right: Node;
	EffectLayer: Node;
	TipLayer: Node;
	Tip_Left: Node;
	banner_skill: Node;
	banner_critical_skill: Node;
	lay_tip_skill: Node;
	ico_tip_attribute: Node;
	lbl_tip: Node;
	tip_level_down: Node;
	tip_level_up: Node;
	tip_priority: Node;
	tip_resist: Node;
	Tip_Right: Node;
	banner_skill_enemy: Node;
	banner_critical_skill_reverse: Node;
	lay_tip_skill_enemy: Node;
	ico_tip_attribute_enemy: Node;
	lbl_tip_enemy: Node;
	tip_level_down_enemy: Node;
	tip_priority_enemy: Node;
	tip_resist_enemy: Node;
	tip_level_up_enemy: Node;
	top: Node;
	pet_avatar: Node;
	layout_petInfo: Node;
	level_bg: Node;
	label_lv: Node;
	ico_attribute: Node;
	label_petName: Node;
	hp_bar: Node;
	hp_inner_bar: Node;
	layout_shield: Node;
	ico_resistance: Node;
	ico_shield_normal: Node;
	label_shield_normal: Node;
	ico_shield_fix: Node;
	label_shield_fix: Node;
	ico_feature: Node;
	layout_level: Node;
	level_atk: Node;
	lbl_atk: Node;
	level_spAtk: Node;
	lbl_spAtk: Node;
	level_def: Node;
	lbl_def: Node;
	level_spDef: Node;
	lbl_spDef: Node;
	level_spd: Node;
	lbl_spd: Node;
	level_hit: Node;
	lbl_hit: Node;
	layout_abnormal: Node;
	ico_abnormal: Node;
	top_banner: Node;
	putong: Node;
	ico_round: Node;
	label_round: Node;
	count_bg: Node;
	count_less_bg: Node;
	label_count: Node;
	pet_avatar_enemy: Node;
	layout_petInfo_enemy: Node;
	level_bg_enemy: Node;
	label_lv_enemy: Node;
	ico_attribute_enemy: Node;
	label_petName_enemy: Node;
	hp_bar_enemy: Node;
	hp_inner_bar_reverse: Node;
	layout_sheild_enemy: Node;
	ico_resistance_enemy: Node;
	ico_shield_normal_enemy: Node;
	label_shield_normal_enemy: Node;
	ico_shield_fix_enemy: Node;
	label_enemy_shield_fix: Node;
	ico_feature_enemy: Node;
	layout_level_enemy: Node;
	level_atk_enemy: Node;
	lbl_atk_enemy: Node;
	level_spAtk_enemy: Node;
	lbl_spAtk_enemy: Node;
	level_def_enemy: Node;
	lbl_def_enemy: Node;
	level_spDef_enemy: Node;
	lbl_spDef_enemy: Node;
	level_spd_enemy: Node;
	lbl_spd_enemy: Node;
	level_hit_enemy: Node;
	lbl_hit_enemy: Node;
	layout_abnormal_enemy: Node;
	ico_abnormal_enemy: Node;
	bottom: Node;
	skill_node: Node;
	layout_skill: Node;
	pets_node: Node;
	layout_pets: Node;
	prop_node: Node;
	layout_prop: Node;
	btn_hp_dark: Node;
	btn_hp: Node;
	btn_pp_dark: Node;
	btn_pp: Node;
	scv_prop: Node;
	scrollBar: Node;
	bar: Node;
	view: Node;
	content: Node;
	bottom_bg: Node;
	pet_change: Node;
	ico_surrender: Node;
	ico_prop: Node;
	btn_back: Node;

	public static URL:string = "assets\gamebundle\prefabs\UI\Battle\BattleUI.prefab"

    onLoad () {
		this.BattleUI = this.node
		this.battle_bg = this.BattleUI.getChildByName("battle_bg");
		this.View = this.BattleUI.getChildByName("View");
		this.PetLayer = this.View.getChildByName("PetLayer");
		this.pet_left = this.PetLayer.getChildByName("pet_left");
		this.pet_right = this.PetLayer.getChildByName("pet_right");
		this.EffectLayer = this.View.getChildByName("EffectLayer");
		this.TipLayer = this.View.getChildByName("TipLayer");
		this.Tip_Left = this.TipLayer.getChildByName("Tip_Left");
		this.banner_skill = this.Tip_Left.getChildByName("banner_skill");
		this.banner_critical_skill = this.banner_skill.getChildByName("banner_critical_skill");
		this.lay_tip_skill = this.banner_skill.getChildByName("lay_tip_skill");
		this.ico_tip_attribute = this.lay_tip_skill.getChildByName("ico_tip_attribute");
		this.lbl_tip = this.lay_tip_skill.getChildByName("lbl_tip");
		this.tip_level_down = this.Tip_Left.getChildByName("tip_level_down");
		this.tip_level_up = this.Tip_Left.getChildByName("tip_level_up");
		this.tip_priority = this.Tip_Left.getChildByName("tip_priority");
		this.tip_resist = this.Tip_Left.getChildByName("tip_resist");
		this.Tip_Right = this.TipLayer.getChildByName("Tip_Right");
		this.banner_skill_enemy = this.Tip_Right.getChildByName("banner_skill_enemy");
		this.banner_critical_skill_reverse = this.banner_skill_enemy.getChildByName("banner_critical_skill_reverse");
		this.lay_tip_skill_enemy = this.banner_skill_enemy.getChildByName("lay_tip_skill_enemy");
		this.ico_tip_attribute_enemy = this.lay_tip_skill_enemy.getChildByName("ico_tip_attribute_enemy");
		this.lbl_tip_enemy = this.lay_tip_skill_enemy.getChildByName("lbl_tip_enemy");
		this.tip_level_down_enemy = this.Tip_Right.getChildByName("tip_level_down_enemy");
		this.tip_priority_enemy = this.Tip_Right.getChildByName("tip_priority_enemy");
		this.tip_resist_enemy = this.Tip_Right.getChildByName("tip_resist_enemy");
		this.tip_level_up_enemy = this.Tip_Right.getChildByName("tip_level_up_enemy");
		this.top = this.View.getChildByName("top");
		this.pet_avatar = this.top.getChildByName("pet_avatar");
		this.layout_petInfo = this.pet_avatar.getChildByName("layout_petInfo");
		this.level_bg = this.layout_petInfo.getChildByName("level_bg");
		this.label_lv = this.level_bg.getChildByName("label_lv");
		this.ico_attribute = this.layout_petInfo.getChildByName("ico_attribute");
		this.label_petName = this.layout_petInfo.getChildByName("label_petName");
		this.hp_bar = this.pet_avatar.getChildByName("hp_bar");
		this.hp_inner_bar = this.hp_bar.getChildByName("hp_inner_bar");
		this.layout_shield = this.pet_avatar.getChildByName("layout_shield");
		this.ico_resistance = this.layout_shield.getChildByName("ico_resistance");
		this.ico_shield_normal = this.layout_shield.getChildByName("ico_shield_normal");
		this.label_shield_normal = this.ico_shield_normal.getChildByName("label_shield_normal");
		this.ico_shield_fix = this.layout_shield.getChildByName("ico_shield_fix");
		this.label_shield_fix = this.ico_shield_fix.getChildByName("label_shield_fix");
		this.ico_feature = this.pet_avatar.getChildByName("ico_feature");
		this.layout_level = this.pet_avatar.getChildByName("layout_level");
		this.level_atk = this.layout_level.getChildByName("level_atk");
		this.lbl_atk = this.level_atk.getChildByName("lbl_atk");
		this.level_spAtk = this.layout_level.getChildByName("level_spAtk");
		this.lbl_spAtk = this.level_spAtk.getChildByName("lbl_spAtk");
		this.level_def = this.layout_level.getChildByName("level_def");
		this.lbl_def = this.level_def.getChildByName("lbl_def");
		this.level_spDef = this.layout_level.getChildByName("level_spDef");
		this.lbl_spDef = this.level_spDef.getChildByName("lbl_spDef");
		this.level_spd = this.layout_level.getChildByName("level_spd");
		this.lbl_spd = this.level_spd.getChildByName("lbl_spd");
		this.level_hit = this.layout_level.getChildByName("level_hit");
		this.lbl_hit = this.level_hit.getChildByName("lbl_hit");
		this.layout_abnormal = this.pet_avatar.getChildByName("layout_abnormal");
		this.ico_abnormal = this.layout_abnormal.getChildByName("ico_abnormal");
		this.top_banner = this.top.getChildByName("top_banner");
		this.putong = this.top_banner.getChildByName("putong");
		this.ico_round = this.top.getChildByName("ico_round");
		this.label_round = this.ico_round.getChildByName("label_round");
		this.count_bg = this.top.getChildByName("count_bg");
		this.count_less_bg = this.count_bg.getChildByName("count_less_bg");
		this.label_count = this.count_bg.getChildByName("label_count");
		this.pet_avatar_enemy = this.top.getChildByName("pet_avatar_enemy");
		this.layout_petInfo_enemy = this.pet_avatar_enemy.getChildByName("layout_petInfo_enemy");
		this.level_bg_enemy = this.layout_petInfo_enemy.getChildByName("level_bg_enemy");
		this.label_lv_enemy = this.level_bg_enemy.getChildByName("label_lv_enemy");
		this.ico_attribute_enemy = this.layout_petInfo_enemy.getChildByName("ico_attribute_enemy");
		this.label_petName_enemy = this.layout_petInfo_enemy.getChildByName("label_petName_enemy");
		this.hp_bar_enemy = this.pet_avatar_enemy.getChildByName("hp_bar_enemy");
		this.hp_inner_bar_reverse = this.hp_bar_enemy.getChildByName("hp_inner_bar_reverse");
		this.layout_sheild_enemy = this.pet_avatar_enemy.getChildByName("layout_sheild_enemy");
		this.ico_resistance_enemy = this.layout_sheild_enemy.getChildByName("ico_resistance_enemy");
		this.ico_shield_normal_enemy = this.layout_sheild_enemy.getChildByName("ico_shield_normal_enemy");
		this.label_shield_normal_enemy = this.ico_shield_normal_enemy.getChildByName("label_shield_normal_enemy");
		this.ico_shield_fix_enemy = this.layout_sheild_enemy.getChildByName("ico_shield_fix_enemy");
		this.label_enemy_shield_fix = this.ico_shield_fix_enemy.getChildByName("label_enemy_shield_fix");
		this.ico_feature_enemy = this.pet_avatar_enemy.getChildByName("ico_feature_enemy");
		this.layout_level_enemy = this.pet_avatar_enemy.getChildByName("layout_level_enemy");
		this.level_atk_enemy = this.layout_level_enemy.getChildByName("level_atk_enemy");
		this.lbl_atk_enemy = this.level_atk_enemy.getChildByName("lbl_atk_enemy");
		this.level_spAtk_enemy = this.layout_level_enemy.getChildByName("level_spAtk_enemy");
		this.lbl_spAtk_enemy = this.level_spAtk_enemy.getChildByName("lbl_spAtk_enemy");
		this.level_def_enemy = this.layout_level_enemy.getChildByName("level_def_enemy");
		this.lbl_def_enemy = this.level_def_enemy.getChildByName("lbl_def_enemy");
		this.level_spDef_enemy = this.layout_level_enemy.getChildByName("level_spDef_enemy");
		this.lbl_spDef_enemy = this.level_spDef_enemy.getChildByName("lbl_spDef_enemy");
		this.level_spd_enemy = this.layout_level_enemy.getChildByName("level_spd_enemy");
		this.lbl_spd_enemy = this.level_spd_enemy.getChildByName("lbl_spd_enemy");
		this.level_hit_enemy = this.layout_level_enemy.getChildByName("level_hit_enemy");
		this.lbl_hit_enemy = this.level_hit_enemy.getChildByName("lbl_hit_enemy");
		this.layout_abnormal_enemy = this.pet_avatar_enemy.getChildByName("layout_abnormal_enemy");
		this.ico_abnormal_enemy = this.layout_abnormal_enemy.getChildByName("ico_abnormal_enemy");
		this.bottom = this.View.getChildByName("bottom");
		this.skill_node = this.bottom.getChildByName("skill_node");
		this.layout_skill = this.skill_node.getChildByName("layout_skill");
		this.pets_node = this.bottom.getChildByName("pets_node");
		this.layout_pets = this.pets_node.getChildByName("layout_pets");
		this.prop_node = this.bottom.getChildByName("prop_node");
		this.layout_prop = this.prop_node.getChildByName("layout_prop");
		this.btn_hp_dark = this.layout_prop.getChildByName("btn_hp_dark");
		this.btn_hp = this.btn_hp_dark.getChildByName("btn_hp");
		this.btn_pp_dark = this.layout_prop.getChildByName("btn_pp_dark");
		this.btn_pp = this.btn_pp_dark.getChildByName("btn_pp");
		this.scv_prop = this.prop_node.getChildByName("scv_prop");
		this.scrollBar = this.scv_prop.getChildByName("scrollBar");
		this.bar = this.scrollBar.getChildByName("bar");
		this.view = this.scv_prop.getChildByName("view");
		this.content = this.view.getChildByName("content");
		this.bottom_bg = this.bottom.getChildByName("bottom_bg");
		this.pet_change = this.bottom_bg.getChildByName("pet_change");
		this.ico_surrender = this.bottom_bg.getChildByName("ico_surrender");
		this.ico_prop = this.bottom_bg.getChildByName("ico_prop");
		this.btn_back = this.ico_prop.getChildByName("btn_back");

    }
}
