import { _decorator, Component, Node, Button, Event } from 'cc';
const { ccclass } = _decorator;

@ccclass
export default class auto_PetDetail extends Component {
	PetDetail: Node;
	BG: Node;
	left_banner: Node;
	lay_fun: Node;
	btn_info_uncheck: Node;
	lbl_info_uncheck: Node;
	btn_info_check: Node;
	lbl_info_check: Node;
	btn_skill_uncheck: Node;
	lbl_skill_uncheck: Node;
	btn_skill_check: Node;
	lbl_skill_check: Node;
	btn_resist_uncheck: Node;
	lbl_resist_uncheck: Node;
	btn_resist_check: Node;
	lbl_resist_check: Node;
	btn_prop_uncheck: Node;
	lbl_prop_uncheck: Node;
	btn_prop_check: Node;
	lbl_prop_check: Node;
	pet_base: Node;
	pet: Node;
	pic_pet: Node;
	petTab: Node;
	pet_Info: Node;
	pet_Info_bg: Node;
	base_info: Node;
	base_level: Node;
	ico_plus_level: Node;
	ico_level: Node;
	txt_level: Node;
	lbl_level: Node;
	base_talent: Node;
	ico_plus_talent: Node;
	ico_talent: Node;
	txt_talent: Node;
	lbl_talent: Node;
	base_learn: Node;
	ico_plus_learn: Node;
	ico_learn: Node;
	txt_learn: Node;
	lbl_learn: Node;
	base_maxHp: Node;
	ico_plus_maxHp: Node;
	ico_maxHp: Node;
	txt_maxHp: Node;
	lbl_maxHp: Node;
	base_character: Node;
	ico_change_character: Node;
	ico_character: Node;
	txt_character: Node;
	lbl_character: Node;
	base_feature: Node;
	ico_change_feature: Node;
	ico_feature: Node;
	txt_feature: Node;
	lbl_feature: Node;
	battle_value: Node;
	battle_atk: Node;
	ico_atk: Node;
	txt_atk: Node;
	lay_learn_atk: Node;
	lbl_atk: Node;
	ico_learn_atk: Node;
	lbl_learn_atk: Node;
	battle_def: Node;
	ico_def: Node;
	txt_def: Node;
	lay_learn_def: Node;
	lbl_def: Node;
	ico_learn_def: Node;
	lbl_learn_def: Node;
	battle_spAtk: Node;
	ico_spAtk: Node;
	txt_spAtk: Node;
	lay_learn_spAtk: Node;
	lbl_spAtk: Node;
	ico_learn_spAtk: Node;
	lbl_learn_spAtk: Node;
	battle_spDef: Node;
	ico_spDef: Node;
	txt_spDef: Node;
	lay_learn_spDef: Node;
	lbl_spDef: Node;
	ico_learn_spDef: Node;
	lbl_learn_spDef: Node;
	battle_spd: Node;
	ico_spd: Node;
	txt_spd: Node;
	lay_learn_spd: Node;
	lbl_spd: Node;
	ico_learn_spd: Node;
	lbl_learn_spd: Node;
	battle_hp: Node;
	ico_hp: Node;
	txt_hp: Node;
	lay_learn_hp: Node;
	lbl_hp: Node;
	ico_learn_hp: Node;
	lbl_learn_hp: Node;
	pet_skill: Node;
	lay_skills: Node;
	banner_skills: Node;
	title_skill: Node;
	skills_bg: Node;
	grid_skill: Node;
	lay_spSkill: Node;
	banner_spSkill: Node;
	title_spSkill: Node;
	spSkill_bg: Node;
	ico_spSkill_bg: Node;
	ico_attribute_spSkill: Node;
	lbl_spSkill: Node;
	cut_line: Node;
	lbl_PP_spSkill: Node;
	lbl_damage_spSkill: Node;
	pet_resist: Node;
	lay_damage_resist: Node;
	banner_damage_resist: Node;
	title_damage: Node;
	damage_resist_bg: Node;
	grid_damage_resist: Node;
	critical_info: Node;
	resist_critical: Node;
	text_critical: Node;
	lbl_critical: Node;
	fix_info: Node;
	resist_fix: Node;
	text_fix: Node;
	lbl_fix: Node;
	percent_info: Node;
	resist_percent: Node;
	text_percent: Node;
	lbl_percent: Node;
	lay_abnormal: Node;
	banner_abnormal: Node;
	title_abnormal: Node;
	abnormal_bg: Node;
	lay_control: Node;
	banner_control: Node;
	control_item1: Node;
	ico_control1: Node;
	lbl_control1: Node;
	num_control1: Node;
	control_item2: Node;
	ico_control2: Node;
	lbl_control2: Node;
	num_control2: Node;
	control_item3: Node;
	ico_control3: Node;
	lbl_control3: Node;
	num_control3: Node;
	lay_week: Node;
	banner_week: Node;
	week_item1: Node;
	ico_week1: Node;
	lbl_week1: Node;
	num_week1: Node;
	week_item2: Node;
	ico_week2: Node;
	lbl_week2: Node;
	num_week2: Node;
	week_item3: Node;
	ico_week3: Node;
	lbl_week3: Node;
	num_week3: Node;
	pet_prop: Node;
	lay_prop: Node;
	banner_prop: Node;
	title_prop: Node;
	prop_bg: Node;
	scv_prop: Node;
	view: Node;
	content: Node;
	top_banner: Node;
	lay_top: Node;
	btn_back: Node;
	common_back: Node;
	lbl_top: Node;

	public static URL:string = "assets\homebundle\prefabs\UI\pet\PetDetail.prefab"

    onLoad () {
		this.PetDetail = this.node
		this.BG = this.PetDetail.getChildByName("BG");
		this.left_banner = this.PetDetail.getChildByName("left_banner");
		this.lay_fun = this.left_banner.getChildByName("lay_fun");
		this.btn_info_uncheck = this.lay_fun.getChildByName("btn_info_uncheck");
		this.lbl_info_uncheck = this.btn_info_uncheck.getChildByName("lbl_info_uncheck");
		this.btn_info_check = this.btn_info_uncheck.getChildByName("btn_info_check");
		this.lbl_info_check = this.btn_info_check.getChildByName("lbl_info_check");
		this.btn_skill_uncheck = this.lay_fun.getChildByName("btn_skill_uncheck");
		this.lbl_skill_uncheck = this.btn_skill_uncheck.getChildByName("lbl_skill_uncheck");
		this.btn_skill_check = this.btn_skill_uncheck.getChildByName("btn_skill_check");
		this.lbl_skill_check = this.btn_skill_check.getChildByName("lbl_skill_check");
		this.btn_resist_uncheck = this.lay_fun.getChildByName("btn_resist_uncheck");
		this.lbl_resist_uncheck = this.btn_resist_uncheck.getChildByName("lbl_resist_uncheck");
		this.btn_resist_check = this.btn_resist_uncheck.getChildByName("btn_resist_check");
		this.lbl_resist_check = this.btn_resist_check.getChildByName("lbl_resist_check");
		this.btn_prop_uncheck = this.lay_fun.getChildByName("btn_prop_uncheck");
		this.lbl_prop_uncheck = this.btn_prop_uncheck.getChildByName("lbl_prop_uncheck");
		this.btn_prop_check = this.btn_prop_uncheck.getChildByName("btn_prop_check");
		this.lbl_prop_check = this.btn_prop_check.getChildByName("lbl_prop_check");
		this.pet_base = this.PetDetail.getChildByName("pet_base");
		this.pet = this.pet_base.getChildByName("pet");
		this.pic_pet = this.pet.getChildByName("pic_pet");
		this.petTab = this.PetDetail.getChildByName("petTab");
		this.pet_Info = this.petTab.getChildByName("pet_Info");
		this.pet_Info_bg = this.pet_Info.getChildByName("pet_Info_bg");
		this.base_info = this.pet_Info_bg.getChildByName("base_info");
		this.base_level = this.base_info.getChildByName("base_level");
		this.ico_plus_level = this.base_level.getChildByName("ico_plus_level");
		this.ico_level = this.base_level.getChildByName("ico_level");
		this.txt_level = this.base_level.getChildByName("txt_level");
		this.lbl_level = this.base_level.getChildByName("lbl_level");
		this.base_talent = this.base_info.getChildByName("base_talent");
		this.ico_plus_talent = this.base_talent.getChildByName("ico_plus_talent");
		this.ico_talent = this.base_talent.getChildByName("ico_talent");
		this.txt_talent = this.base_talent.getChildByName("txt_talent");
		this.lbl_talent = this.base_talent.getChildByName("lbl_talent");
		this.base_learn = this.base_info.getChildByName("base_learn");
		this.ico_plus_learn = this.base_learn.getChildByName("ico_plus_learn");
		this.ico_learn = this.base_learn.getChildByName("ico_learn");
		this.txt_learn = this.base_learn.getChildByName("txt_learn");
		this.lbl_learn = this.base_learn.getChildByName("lbl_learn");
		this.base_maxHp = this.base_info.getChildByName("base_maxHp");
		this.ico_plus_maxHp = this.base_maxHp.getChildByName("ico_plus_maxHp");
		this.ico_maxHp = this.base_maxHp.getChildByName("ico_maxHp");
		this.txt_maxHp = this.base_maxHp.getChildByName("txt_maxHp");
		this.lbl_maxHp = this.base_maxHp.getChildByName("lbl_maxHp");
		this.base_character = this.base_info.getChildByName("base_character");
		this.ico_change_character = this.base_character.getChildByName("ico_change_character");
		this.ico_character = this.base_character.getChildByName("ico_character");
		this.txt_character = this.base_character.getChildByName("txt_character");
		this.lbl_character = this.base_character.getChildByName("lbl_character");
		this.base_feature = this.base_info.getChildByName("base_feature");
		this.ico_change_feature = this.base_feature.getChildByName("ico_change_feature");
		this.ico_feature = this.base_feature.getChildByName("ico_feature");
		this.txt_feature = this.base_feature.getChildByName("txt_feature");
		this.lbl_feature = this.base_feature.getChildByName("lbl_feature");
		this.battle_value = this.pet_Info_bg.getChildByName("battle_value");
		this.battle_atk = this.battle_value.getChildByName("battle_atk");
		this.ico_atk = this.battle_atk.getChildByName("ico_atk");
		this.txt_atk = this.battle_atk.getChildByName("txt_atk");
		this.lay_learn_atk = this.battle_atk.getChildByName("lay_learn_atk");
		this.lbl_atk = this.lay_learn_atk.getChildByName("lbl_atk");
		this.ico_learn_atk = this.lay_learn_atk.getChildByName("ico_learn_atk");
		this.lbl_learn_atk = this.lay_learn_atk.getChildByName("lbl_learn_atk");
		this.battle_def = this.battle_value.getChildByName("battle_def");
		this.ico_def = this.battle_def.getChildByName("ico_def");
		this.txt_def = this.battle_def.getChildByName("txt_def");
		this.lay_learn_def = this.battle_def.getChildByName("lay_learn_def");
		this.lbl_def = this.lay_learn_def.getChildByName("lbl_def");
		this.ico_learn_def = this.lay_learn_def.getChildByName("ico_learn_def");
		this.lbl_learn_def = this.lay_learn_def.getChildByName("lbl_learn_def");
		this.battle_spAtk = this.battle_value.getChildByName("battle_spAtk");
		this.ico_spAtk = this.battle_spAtk.getChildByName("ico_spAtk");
		this.txt_spAtk = this.battle_spAtk.getChildByName("txt_spAtk");
		this.lay_learn_spAtk = this.battle_spAtk.getChildByName("lay_learn_spAtk");
		this.lbl_spAtk = this.lay_learn_spAtk.getChildByName("lbl_spAtk");
		this.ico_learn_spAtk = this.lay_learn_spAtk.getChildByName("ico_learn_spAtk");
		this.lbl_learn_spAtk = this.lay_learn_spAtk.getChildByName("lbl_learn_spAtk");
		this.battle_spDef = this.battle_value.getChildByName("battle_spDef");
		this.ico_spDef = this.battle_spDef.getChildByName("ico_spDef");
		this.txt_spDef = this.battle_spDef.getChildByName("txt_spDef");
		this.lay_learn_spDef = this.battle_spDef.getChildByName("lay_learn_spDef");
		this.lbl_spDef = this.lay_learn_spDef.getChildByName("lbl_spDef");
		this.ico_learn_spDef = this.lay_learn_spDef.getChildByName("ico_learn_spDef");
		this.lbl_learn_spDef = this.lay_learn_spDef.getChildByName("lbl_learn_spDef");
		this.battle_spd = this.battle_value.getChildByName("battle_spd");
		this.ico_spd = this.battle_spd.getChildByName("ico_spd");
		this.txt_spd = this.battle_spd.getChildByName("txt_spd");
		this.lay_learn_spd = this.battle_spd.getChildByName("lay_learn_spd");
		this.lbl_spd = this.lay_learn_spd.getChildByName("lbl_spd");
		this.ico_learn_spd = this.lay_learn_spd.getChildByName("ico_learn_spd");
		this.lbl_learn_spd = this.lay_learn_spd.getChildByName("lbl_learn_spd");
		this.battle_hp = this.battle_value.getChildByName("battle_hp");
		this.ico_hp = this.battle_hp.getChildByName("ico_hp");
		this.txt_hp = this.battle_hp.getChildByName("txt_hp");
		this.lay_learn_hp = this.battle_hp.getChildByName("lay_learn_hp");
		this.lbl_hp = this.lay_learn_hp.getChildByName("lbl_hp");
		this.ico_learn_hp = this.lay_learn_hp.getChildByName("ico_learn_hp");
		this.lbl_learn_hp = this.lay_learn_hp.getChildByName("lbl_learn_hp");
		this.pet_skill = this.petTab.getChildByName("pet_skill");
		this.lay_skills = this.pet_skill.getChildByName("lay_skills");
		this.banner_skills = this.lay_skills.getChildByName("banner_skills");
		this.title_skill = this.banner_skills.getChildByName("title_skill");
		this.skills_bg = this.lay_skills.getChildByName("skills_bg");
		this.grid_skill = this.skills_bg.getChildByName("grid_skill");
		this.lay_spSkill = this.pet_skill.getChildByName("lay_spSkill");
		this.banner_spSkill = this.lay_spSkill.getChildByName("banner_spSkill");
		this.title_spSkill = this.banner_spSkill.getChildByName("title_spSkill");
		this.spSkill_bg = this.lay_spSkill.getChildByName("spSkill_bg");
		this.ico_spSkill_bg = this.spSkill_bg.getChildByName("ico_spSkill_bg");
		this.ico_attribute_spSkill = this.ico_spSkill_bg.getChildByName("ico_attribute_spSkill");
		this.lbl_spSkill = this.spSkill_bg.getChildByName("lbl_spSkill");
		this.cut_line = this.spSkill_bg.getChildByName("cut_line");
		this.lbl_PP_spSkill = this.spSkill_bg.getChildByName("lbl_PP_spSkill");
		this.lbl_damage_spSkill = this.spSkill_bg.getChildByName("lbl_damage_spSkill");
		this.pet_resist = this.petTab.getChildByName("pet_resist");
		this.lay_damage_resist = this.pet_resist.getChildByName("lay_damage_resist");
		this.banner_damage_resist = this.lay_damage_resist.getChildByName("banner_damage_resist");
		this.title_damage = this.banner_damage_resist.getChildByName("title_damage");
		this.damage_resist_bg = this.lay_damage_resist.getChildByName("damage_resist_bg");
		this.grid_damage_resist = this.damage_resist_bg.getChildByName("grid_damage_resist");
		this.critical_info = this.grid_damage_resist.getChildByName("critical_info");
		this.resist_critical = this.critical_info.getChildByName("resist_critical");
		this.text_critical = this.critical_info.getChildByName("text_critical");
		this.lbl_critical = this.critical_info.getChildByName("lbl_critical");
		this.fix_info = this.grid_damage_resist.getChildByName("fix_info");
		this.resist_fix = this.fix_info.getChildByName("resist_fix");
		this.text_fix = this.fix_info.getChildByName("text_fix");
		this.lbl_fix = this.fix_info.getChildByName("lbl_fix");
		this.percent_info = this.grid_damage_resist.getChildByName("percent_info");
		this.resist_percent = this.percent_info.getChildByName("resist_percent");
		this.text_percent = this.percent_info.getChildByName("text_percent");
		this.lbl_percent = this.percent_info.getChildByName("lbl_percent");
		this.lay_abnormal = this.pet_resist.getChildByName("lay_abnormal");
		this.banner_abnormal = this.lay_abnormal.getChildByName("banner_abnormal");
		this.title_abnormal = this.banner_abnormal.getChildByName("title_abnormal");
		this.abnormal_bg = this.lay_abnormal.getChildByName("abnormal_bg");
		this.lay_control = this.abnormal_bg.getChildByName("lay_control");
		this.banner_control = this.lay_control.getChildByName("banner_control");
		this.control_item1 = this.lay_control.getChildByName("control_item1");
		this.ico_control1 = this.control_item1.getChildByName("ico_control1");
		this.lbl_control1 = this.control_item1.getChildByName("lbl_control1");
		this.num_control1 = this.control_item1.getChildByName("num_control1");
		this.control_item2 = this.lay_control.getChildByName("control_item2");
		this.ico_control2 = this.control_item2.getChildByName("ico_control2");
		this.lbl_control2 = this.control_item2.getChildByName("lbl_control2");
		this.num_control2 = this.control_item2.getChildByName("num_control2");
		this.control_item3 = this.lay_control.getChildByName("control_item3");
		this.ico_control3 = this.control_item3.getChildByName("ico_control3");
		this.lbl_control3 = this.control_item3.getChildByName("lbl_control3");
		this.num_control3 = this.control_item3.getChildByName("num_control3");
		this.lay_week = this.abnormal_bg.getChildByName("lay_week");
		this.banner_week = this.lay_week.getChildByName("banner_week");
		this.week_item1 = this.lay_week.getChildByName("week_item1");
		this.ico_week1 = this.week_item1.getChildByName("ico_week1");
		this.lbl_week1 = this.week_item1.getChildByName("lbl_week1");
		this.num_week1 = this.week_item1.getChildByName("num_week1");
		this.week_item2 = this.lay_week.getChildByName("week_item2");
		this.ico_week2 = this.week_item2.getChildByName("ico_week2");
		this.lbl_week2 = this.week_item2.getChildByName("lbl_week2");
		this.num_week2 = this.week_item2.getChildByName("num_week2");
		this.week_item3 = this.lay_week.getChildByName("week_item3");
		this.ico_week3 = this.week_item3.getChildByName("ico_week3");
		this.lbl_week3 = this.week_item3.getChildByName("lbl_week3");
		this.num_week3 = this.week_item3.getChildByName("num_week3");
		this.pet_prop = this.petTab.getChildByName("pet_prop");
		this.lay_prop = this.pet_prop.getChildByName("lay_prop");
		this.banner_prop = this.lay_prop.getChildByName("banner_prop");
		this.title_prop = this.banner_prop.getChildByName("title_prop");
		this.prop_bg = this.lay_prop.getChildByName("prop_bg");
		this.scv_prop = this.prop_bg.getChildByName("scv_prop");
		this.view = this.scv_prop.getChildByName("view");
		this.content = this.view.getChildByName("content");
		this.top_banner = this.PetDetail.getChildByName("top_banner");
		this.lay_top = this.top_banner.getChildByName("lay_top");
		this.btn_back = this.lay_top.getChildByName("btn_back");
		this.common_back = this.btn_back.getChildByName("common_back");
		this.lbl_top = this.lay_top.getChildByName("lbl_top");

    }
}
